const stringKeys = {
  'score.add': '',
  'score.addSubtitle': '',
  'score.edit': '',
  'score.editSubtitle': '',
  'score.yourScore': '',
  'score.requiredMessage': '',
  'score.dialogSave': '',
  'score.dialogCancel': '',
  'scoreboard.overall': '',
  'scoreboard.day': '',
  'scoreboard.week': '',
  'scoreboard.month': '',
  'notifications.topRankNotificationTitle': '',
  'notifications.lowerRankNotificationTitle': '',
};
